languageCode = "en-au"
languageName = "English (Australia)"
displayName = ":flag-au:"
isoCode = "en-AU"
weight = 1
rtl = false

title = "Runnersworld Track Meetings"
#logo = "img/logo.jpg"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
copyright = "&copy; 2022 Runnersworld Track Meetings"

dateFormat = "2 January 2006"

[author]
  name = "Runnersworld Track Meetings Utrecht"
  #image = "img/logo.jpg"
  headline = "Not your ordinary theme!"
  bio = "De Runnersworld Track Meetings worden georganiseerd vanuit de atletiekverenigingen [AV Phoenix](https://avphoenix.nl/) en [U-Track](https://www.u-track.nl/). De Runnersworld Track Meetings worden mogelijk gemaakt door [Runnersworld Utrecht](https://www.runnersworld.nl/vestigingen/utrecht/). De winkel bevindt zich in Stadion Galgenwaard, op [loopafstand](https://www.google.nl/maps/dir/Maarschalkerweerd,+Mytylweg+79,+3585+LK+Utrecht/Runnersworld+Utrecht+-+Hardloopwinkel,+Herculesplein,+Utrecht/@52.0781809,5.1469583,16.22z/data=!4m14!4m13!1m5!1m1!1s0x47c6661e793ec98d:0x648c6411bb37315d!2m2!1d5.1565129!2d52.0788908!1m5!1m1!1s0x47c66602a77606ef:0x2b33d5b01ce3180e!2m2!1d5.1464833!2d52.0789945!3e2) van atletiekbaan Maarschalkerweerd."
  links = [
    { instagram = "https://www.instagram.com/trackmeetingsutrecht/" },
    { twitter = "https://twitter.com/TrackMeetings/" },
    { facebook = "https://www.facebook.com/trackmeetings/" },
    { linkedin = "https://www.linkedin.com/company/runnersworld-utrecht-track-meetings/" },
  ]
